import { Inter } from "next/font/google";
import Navbar from '../components/Navbar'; // Adjust the path if needed
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* This ensures Navbar is rendered on all pages */}
        <main>{children}</main>
      </body>
    </html>
  );
}
